set_property PACKAGE_PIN H2 [get_ports ALE]
set_property PACKAGE_PIN G6 [get_ports {CEN[7]}]
set_property PACKAGE_PIN G9 [get_ports {CEN[6]}]
set_property PACKAGE_PIN J5 [get_ports {CEN[5]}]
set_property PACKAGE_PIN K8 [get_ports {CEN[4]}]
set_property PACKAGE_PIN H4 [get_ports {CEN[3]}]
set_property PACKAGE_PIN K6 [get_ports {CEN[2]}]
set_property PACKAGE_PIN F4 [get_ports {CEN[1]}]
set_property PACKAGE_PIN F5 [get_ports {CEN[0]}]
set_property PACKAGE_PIN M2 [get_ports CLE]
set_property PACKAGE_PIN D4 [get_ports {DQ[0]}]
set_property PACKAGE_PIN C4 [get_ports {DQ[1]}]
set_property PACKAGE_PIN B4 [get_ports {DQ[2]}]
set_property PACKAGE_PIN A4 [get_ports {DQ[3]}]
set_property PACKAGE_PIN D3 [get_ports {DQ[4]}]
set_property PACKAGE_PIN C3 [get_ports {DQ[5]}]
set_property PACKAGE_PIN F3 [get_ports {DQ[6]}]
set_property PACKAGE_PIN E3 [get_ports {DQ[7]}]
set_property PACKAGE_PIN B5 [get_ports DQS]
set_property PACKAGE_PIN E6 [get_ports NAND_CLK]
set_property PACKAGE_PIN D5 [get_ports CLK_sysClkN]
set_property PACKAGE_PIN E5 [get_ports CLK_sysClkP]
set_property PACKAGE_PIN P14 [get_ports RST_N_sysRstn]
set_property PACKAGE_PIN M1 [get_ports WPN]
set_property PACKAGE_PIN N3 [get_ports WRN]

set_property PACKAGE_PIN K2 [get_ports {DEBUG[0]}]
set_property PACKAGE_PIN L3 [get_ports {DEBUG[1]}]
set_property PACKAGE_PIN J1 [get_ports {DEBUG[2]}]
set_property PACKAGE_PIN K1 [get_ports {DEBUG[3]}]
set_property PACKAGE_PIN M5 [get_ports {DEBUG[4]}]
set_property PACKAGE_PIN M6 [get_ports {DEBUG[5]}]
set_property PACKAGE_PIN N6 [get_ports {DEBUG[6]}]
set_property PACKAGE_PIN N7 [get_ports {DEBUG[7]}]

set_property PACKAGE_PIN K5 [get_ports {DEBUG90[0]}]
set_property PACKAGE_PIN L5 [get_ports {DEBUG90[1]}]
set_property PACKAGE_PIN L4 [get_ports {DEBUG90[2]}]
set_property PACKAGE_PIN M4 [get_ports {DEBUG90[3]}]
set_property PACKAGE_PIN L7 [get_ports {DEBUG90[4]}]
set_property PACKAGE_PIN M7 [get_ports {DEBUG90[5]}]
set_property PACKAGE_PIN J3 [get_ports {DEBUG90[6]}]
set_property PACKAGE_PIN K3 [get_ports {DEBUG90[7]}]


set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DEBUG90[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {DQ[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DQ[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DQ[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DQ[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DQ[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DQ[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DQ[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DQ[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CEN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports RST_N_sysRstn]
set_property IOSTANDARD LVDS_25 [get_ports CLK_sysClkP]
set_property IOSTANDARD LVDS_25 [get_ports CLK_sysClkN]
set_property IOSTANDARD LVCMOS18 [get_ports NAND_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports DQS]
set_property IOSTANDARD LVCMOS18 [get_ports CLE]
set_property IOSTANDARD LVCMOS18 [get_ports ALE]
set_property IOSTANDARD LVCMOS18 [get_ports WRN]
set_property IOSTANDARD LVCMOS18 [get_ports WPN]


#iodelay group. Note that for IDELAYE2, the group is specified in the verilog file 
#set_property IODELAY_GROUP IODELAY_NAND [get_cells */idelayCtrl]

#differential clocks only need one constraint
create_clock -name CLK_sysClkP -period 10.0 [get_ports CLK_sysClkP]




